### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by Jineeshak** [rebootuser/LinEnum#20]
Check /etc/passwd writable

**Comment by rebootuser** [comment]
There are a few files that we might be interested in. After thinking about this, instead of pulling each out I think it's covered in 'can we read/write sensitive files' output, example below and hence closing request at this stage.

`[-] Can we read/write sensitive files:`
`-rw-r--r-- 1 root root 1808 Nov 20 16:31 /etc/passwd`
`-rw-r--r-- 1 root root 842 Nov 20 16:31 /etc/group`
`-rw-r--r-- 1 root root 596 Jul 10  2018 /etc/profile`
`-rw-r----- 1 root shadow 1335 Nov 20 16:40 /etc/shadow`
